/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alpha.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "fullscreen.h"
#include "movestack.h"
#include "pertag.h"
#include "scratchpad.h"
#include "shiftviewclients.h"
#include "stacker.h"
#include "sticky.h"
#include "swallow.h"
#include "swaptags.h"
#include "vanitygaps.h"
#include "zoomswap.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_tile.h"

